"""初始化全部35张业务表

Revision ID: 420bb62f1724
Revises: 
Create Date: 2026-06-26 08:15:07.919440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '420bb62f1724'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('support_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False, comment='用户提问'),
    sa.Column('answer', sa.Text(), nullable=True, comment='AI 回答'),
    sa.Column('category', sa.String(length=32), nullable=True, comment='问题分类'),
    sa.Column('need_manual', sa.Integer(), nullable=False, comment='是否需要转人工'),
    sa.Column('input_mode', sa.Enum('text', 'voice', name='support_input_mode_enum'), nullable=False, comment='输入方式'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('idx_category'), table_name='customer_service_sessions')
    op.drop_index(op.f('idx_need_manual'), table_name='customer_service_sessions')
    op.drop_index(op.f('idx_user_created'), table_name='customer_service_sessions')
    op.drop_table('customer_service_sessions')
    op.drop_index(op.f('idx_parent'), table_name='discussion_comments')
    op.drop_index(op.f('idx_topic_created'), table_name='discussion_comments')
    op.drop_table('discussion_comments')
    op.drop_index(op.f('idx_challenge_score'), table_name='challenge_participations')
    op.drop_index(op.f('uk_challenge_user'), table_name='challenge_participations')
    op.drop_table('challenge_participations')
    op.drop_index(op.f('idx_category'), table_name='discussion_topics')
    op.drop_index(op.f('idx_is_pinned_created'), table_name='discussion_topics')
    op.drop_table('discussion_topics')
    op.drop_index(op.f('uk_config_key'), table_name='system_config')
    op.drop_table('system_config')
    op.drop_index(op.f('idx_status_expires'), table_name='challenge_topics')
    op.drop_table('challenge_topics')
    op.alter_column('admin_logs', 'action',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment='操作类型',
               existing_comment='操作类型：user_disable/content_edit/class_create等',
               existing_nullable=False)
    op.alter_column('admin_logs', 'target_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='操作对象类型',
               existing_comment='操作对象类型：user/content/class等',
               existing_nullable=False)
    op.alter_column('admin_logs', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='操作时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_action'), table_name='admin_logs')
    op.drop_index(op.f('idx_admin_created'), table_name='admin_logs')
    op.drop_index(op.f('idx_target'), table_name='admin_logs')
    op.drop_table_comment(
        'admin_logs',
        existing_comment='管理员操作日志表',
        schema=None
    )
    op.drop_column('admin_logs', 'ip_address')
    op.alter_column('assessment_questions', 'options',
               existing_type=mysql.JSON(),
               comment=None,
               existing_comment='客观题选项数组，每题4个选项',
               existing_nullable=False)
    op.alter_column('assessment_questions', 'correct_option',
               existing_type=mysql.TINYINT(),
               type_=sa.Integer(),
               existing_comment='正确选项序号 1-4',
               existing_nullable=False)
    op.alter_column('assessment_questions', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('assessment_questions', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('assessment_questions', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_dimension_difficulty'), table_name='assessment_questions')
    op.drop_index(op.f('idx_is_active'), table_name='assessment_questions')
    op.drop_table_comment(
        'assessment_questions',
        existing_comment='测评题库表',
        schema=None
    )
    op.alter_column('assessment_records', 'session_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               comment='测评会话UUID',
               existing_comment='测评会话UUID，一次测评对应一个',
               existing_nullable=False)
    op.alter_column('assessment_records', 'user_answer',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='选项ID 或 录音URL',
               existing_comment='用户答案（选项ID 或 录音URL）',
               existing_nullable=True)
    op.alter_column('assessment_records', 'is_correct',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Integer(),
               existing_comment='客观题是否正确，口语题为NULL',
               existing_nullable=True)
    op.alter_column('assessment_records', 'transcript',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='口语题转写文本',
               existing_comment='口语题Whisper转写文本',
               existing_nullable=True)
    op.alter_column('assessment_records', 'question_order',
               existing_type=mysql.TINYINT(),
               type_=sa.Integer(),
               existing_comment='题号 1-10',
               existing_nullable=False)
    op.alter_column('assessment_records', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               comment=None,
               existing_comment='作答时间',
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_session'), table_name='assessment_records')
    op.drop_index(op.f('idx_user_session'), table_name='assessment_records')
    op.drop_table_comment(
        'assessment_records',
        existing_comment='测评记录表',
        schema=None
    )
    op.alter_column('assignment_submissions', 'score',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               comment='AI评分',
               existing_comment='AI评分 0-100',
               existing_nullable=True)
    op.alter_column('assignment_submissions', 'teacher_feedback',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='教师点评',
               existing_comment='教师点评文字',
               existing_nullable=True)
    op.alter_column('assignment_submissions', 'teacher_score',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               comment='教师评分',
               existing_comment='教师评分 0-100',
               existing_nullable=True)
    op.alter_column('assignment_submissions', 'status',
               existing_type=mysql.ENUM('submitted', 'reviewed', collation='utf8mb4_unicode_ci'),
               nullable=True,
               existing_server_default=sa.text("'submitted'"))
    op.drop_index(op.f('idx_status'), table_name='assignment_submissions')
    op.drop_index(op.f('uk_assignment_user'), table_name='assignment_submissions')
    op.drop_table_comment(
        'assignment_submissions',
        existing_comment='作业提交表',
        schema=None
    )
    op.alter_column('assignments', 'title',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment='作业标题',
               existing_nullable=False)
    op.alter_column('assignments', 'description',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='作业描述',
               existing_nullable=True)
    op.alter_column('assignments', 'completion_rate',
               existing_type=mysql.DECIMAL(precision=4, scale=1),
               nullable=True,
               existing_comment='完成率百分比',
               existing_server_default=sa.text("'0.0'"))
    op.drop_index(op.f('idx_class_due'), table_name='assignments')
    op.drop_index(op.f('idx_due_date'), table_name='assignments')
    op.drop_table_comment(
        'assignments',
        existing_comment='作业表',
        schema=None
    )
    op.drop_index(op.f('idx_user'), table_name='class_students')
    op.drop_index(op.f('uk_class_user'), table_name='class_students')
    op.drop_table_comment(
        'class_students',
        existing_comment='班级学生表',
        schema=None
    )
    op.alter_column('classes', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment='班级名称',
               existing_nullable=False)
    op.alter_column('classes', 'description',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               comment='班级描述',
               existing_nullable=True,
               existing_server_default=sa.text("''"))
    op.alter_column('classes', 'invite_code',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment='邀请码',
               existing_comment='邀请码（唯一）',
               existing_nullable=False)
    op.alter_column('classes', 'student_count',
               existing_type=mysql.SMALLINT(),
               nullable=True,
               comment='学生数',
               existing_server_default=sa.text("'0'"))
    op.alter_column('classes', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Integer(),
               nullable=True,
               comment='0-停用 1-启用',
               existing_server_default=sa.text("'1'"))
    op.drop_index(op.f('idx_is_active'), table_name='classes')
    op.drop_index(op.f('idx_teacher'), table_name='classes')
    op.drop_table_comment(
        'classes',
        existing_comment='班级表',
        schema=None
    )
    op.add_column('conversation_messages', sa.Column('round_number', sa.Integer(), nullable=False, comment='轮次序号 1-N'))
    op.add_column('conversation_messages', sa.Column('content_text', sa.Text(), nullable=False, comment='消息文本'))
    op.add_column('conversation_messages', sa.Column('score', sa.DECIMAL(precision=5, scale=2), nullable=True, comment='单轮得分'))
    op.alter_column('conversation_messages', 'role',
               existing_type=mysql.ENUM('user', 'ai', collation='utf8mb4_unicode_ci'),
               type_=sa.Enum('user', 'assistant', name='message_role_enum'),
               comment='消息角色',
               existing_nullable=False)
    op.alter_column('conversation_messages', 'audio_url',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               comment='音频 URL（用户录音或 TTS）',
               existing_comment='语音消息文件路径',
               existing_nullable=True)
    op.alter_column('conversation_messages', 'grammar_check',
               existing_type=mysql.JSON(),
               comment='语法纠错结果 JSON',
               existing_comment='语法检查结果JSON（含纠错+润色）',
               existing_nullable=True)
    op.alter_column('conversation_messages', 'fluency_scores',
               existing_type=mysql.JSON(),
               comment='流利度五维评分 JSON',
               existing_comment='流利度五维评分JSON',
               existing_nullable=True)
    op.alter_column('conversation_messages', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               comment=None,
               existing_comment='消息时间',
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_session_order'), table_name='conversation_messages')
    op.drop_table_comment(
        'conversation_messages',
        existing_comment='对话消息表',
        schema=None
    )
    op.drop_column('conversation_messages', 'confidence')
    op.drop_column('conversation_messages', 'message_order')
    op.drop_column('conversation_messages', 'text')
    op.add_column('conversation_sessions', sa.Column('session_uuid', sa.String(length=36), nullable=False, comment='会话 UUID'))
    op.add_column('conversation_sessions', sa.Column('scene', sa.Enum('self_intro', 'directions', 'shopping', 'restaurant', 'free', name='conversation_scene_enum'), nullable=False, comment='对话场景'))
    op.add_column('conversation_sessions', sa.Column('cefr_level', sa.String(length=5), nullable=True, comment='用户 CEFR 等级（难度自适应依据）'))
    op.add_column('conversation_sessions', sa.Column('round_count', sa.Integer(), nullable=True, comment='已完成轮数'))
    op.add_column('conversation_sessions', sa.Column('score_pronunciation', sa.DECIMAL(precision=5, scale=2), nullable=True, comment='发音得分'))
    op.add_column('conversation_sessions', sa.Column('score_grammar', sa.DECIMAL(precision=5, scale=2), nullable=True, comment='语法得分'))
    op.add_column('conversation_sessions', sa.Column('score_vocabulary', sa.DECIMAL(precision=5, scale=2), nullable=True, comment='词汇得分'))
    op.add_column('conversation_sessions', sa.Column('score_engagement', sa.DECIMAL(precision=5, scale=2), nullable=True, comment='参与度得分'))
    op.add_column('conversation_sessions', sa.Column('score_overall', sa.DECIMAL(precision=5, scale=2), nullable=True, comment='综合分'))
    op.add_column('conversation_sessions', sa.Column('improvement_suggestions', sa.Text(), nullable=True, comment='改进建议'))
    op.add_column('conversation_sessions', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.alter_column('conversation_sessions', 'role_id',
               existing_type=mysql.INTEGER(),
               comment='角色扮演角色 ID（仅角色扮演场景）',
               existing_comment='角色ID（角色扮演会话用），NULL为普通对话',
               existing_nullable=True)
    op.alter_column('conversation_sessions', 'started_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               comment=None,
               existing_comment='对话开始时间',
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('conversation_sessions', 'ended_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='对话结束时间',
               existing_nullable=True)
    op.alter_column('conversation_sessions', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_scene'), table_name='conversation_sessions')
    op.drop_index(op.f('idx_user_status'), table_name='conversation_sessions')
    op.create_unique_constraint(None, 'conversation_sessions', ['session_uuid'])
    op.drop_table_comment(
        'conversation_sessions',
        existing_comment='对话会话表',
        schema=None
    )
    op.drop_column('conversation_sessions', 'scene_id')
    op.drop_column('conversation_sessions', 'total_score')
    op.drop_column('conversation_sessions', 'score_breakdown')
    op.alter_column('dubbing_content', 'source',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment=None,
               existing_comment='来源：电影/动画/演讲名称',
               existing_nullable=True,
               existing_server_default=sa.text("''"))
    op.alter_column('dubbing_content', 'duration',
               existing_type=mysql.TINYINT(),
               type_=sa.SmallInteger(),
               existing_comment='片段时长（秒）5-20',
               existing_nullable=False)
    op.alter_column('dubbing_content', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.drop_index(op.f('idx_difficulty'), table_name='dubbing_content')
    op.drop_index(op.f('idx_is_active'), table_name='dubbing_content')
    op.drop_table_comment(
        'dubbing_content',
        existing_comment='配音内容表',
        schema=None
    )
    op.alter_column('dubbing_records', 'pronunciation_score',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               comment=None,
               existing_comment='发音相似度 0-100',
               existing_nullable=True)
    op.alter_column('dubbing_records', 'intonation_score',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               comment=None,
               existing_comment='语调相似度 0-100',
               existing_nullable=True)
    op.alter_column('dubbing_records', 'emotion_score',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               comment=None,
               existing_comment='情感匹配度 0-100',
               existing_nullable=True)
    op.alter_column('dubbing_records', 'total_score',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               comment=None,
               existing_comment='综合评分 0-100',
               existing_nullable=True)
    op.alter_column('dubbing_records', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='配音时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_user_created'), table_name='dubbing_records')
    op.drop_table_comment(
        'dubbing_records',
        existing_comment='配音记录表',
        schema=None
    )
    op.add_column('faq_entries', sa.Column('sort_order', sa.Integer(), nullable=True, comment='排序权重'))
    op.alter_column('faq_entries', 'question',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               comment='问题文本',
               existing_nullable=False)
    op.alter_column('faq_entries', 'answer',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='回答文本',
               existing_nullable=False)
    op.alter_column('faq_entries', 'category',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               type_=sa.Enum('product_use', 'study_advice', 'tech_issue', 'refund', 'general', name='faq_category_enum'),
               comment='问题分类',
               existing_comment='分类：product_use/study_advice/tech_issue/account',
               existing_nullable=False)
    op.alter_column('faq_entries', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('faq_entries', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('faq_entries', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_category_priority'), table_name='faq_entries')
    op.drop_index(op.f('idx_is_active'), table_name='faq_entries')
    op.drop_table_comment(
        'faq_entries',
        existing_comment='FAQ条目表',
        schema=None
    )
    op.drop_column('faq_entries', 'priority')
    op.alter_column('group_members', 'role',
               existing_type=mysql.ENUM('owner', 'member', collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=10),
               nullable=True,
               comment='owner/member',
               existing_server_default=sa.text("'member'"))
    op.drop_index(op.f('idx_user'), table_name='group_members')
    op.drop_index(op.f('uk_group_user'), table_name='group_members')
    op.drop_table_comment(
        'group_members',
        existing_comment='小组成员表',
        schema=None
    )
    op.alter_column('groups', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment='小组名称',
               existing_nullable=False)
    op.alter_column('groups', 'description',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               comment='小组简介',
               existing_nullable=True,
               existing_server_default=sa.text("''"))
    op.alter_column('groups', 'level_range',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment='等级范围如 A1-C1',
               existing_comment='等级范围如 A1-B1',
               existing_nullable=True,
               existing_server_default=sa.text("''"))
    op.alter_column('groups', 'schedule',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment='活动时间',
               existing_nullable=True,
               existing_server_default=sa.text("''"))
    op.alter_column('groups', 'tags',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment='标签，逗号分隔',
               existing_nullable=True,
               existing_server_default=sa.text("''"))
    op.alter_column('groups', 'max_members',
               existing_type=mysql.SMALLINT(),
               nullable=True,
               comment='最大人数',
               existing_server_default=sa.text("'20'"))
    op.alter_column('groups', 'member_count',
               existing_type=mysql.SMALLINT(),
               nullable=True,
               comment='成员数',
               existing_server_default=sa.text("'0'"))
    op.alter_column('groups', 'is_archived',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               comment='是否归档',
               existing_comment='0-正常 1-已归档',
               existing_server_default=sa.text("'0'"))
    op.drop_index(op.f('idx_is_archived'), table_name='groups')
    op.drop_index(op.f('idx_level_range'), table_name='groups')
    op.drop_table_comment(
        'groups',
        existing_comment='学习小组表',
        schema=None
    )
    op.add_column('learning_materials', sa.Column('description', sa.Text(), nullable=True, comment='资料描述'))
    op.add_column('learning_materials', sa.Column('material_type', sa.Enum('video', 'article', 'audio', name='material_type_enum'), nullable=False, comment='资料类型'))
    op.add_column('learning_materials', sa.Column('cefr_level', sa.String(length=5), nullable=False, comment='CEFR 难度'))
    op.add_column('learning_materials', sa.Column('category', sa.String(length=64), nullable=True, comment='分类标签'))
    op.add_column('learning_materials', sa.Column('duration_seconds', sa.Integer(), nullable=True, comment='时长（秒），视频/音频适用'))
    op.add_column('learning_materials', sa.Column('focus_dimensions', sa.JSON(), nullable=True, comment='聚焦维度：listening/speaking/reading/grammar'))
    op.alter_column('learning_materials', 'title',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment='资料标题',
               existing_nullable=False)
    op.alter_column('learning_materials', 'url',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               comment='资料链接',
               existing_nullable=False)
    op.alter_column('learning_materials', 'tags',
               existing_type=mysql.JSON(),
               comment='标签数组',
               existing_comment='内容标签数组JSON',
               existing_nullable=True)
    op.alter_column('learning_materials', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('learning_materials', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('learning_materials', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_dimension'), table_name='learning_materials')
    op.drop_index(op.f('idx_is_active'), table_name='learning_materials')
    op.drop_index(op.f('idx_type_difficulty'), table_name='learning_materials')
    op.drop_table_comment(
        'learning_materials',
        existing_comment='学习资料表',
        schema=None
    )
    op.drop_column('learning_materials', 'difficulty')
    op.drop_column('learning_materials', 'related_dimension')
    op.drop_column('learning_materials', 'type')
    op.drop_column('learning_materials', 'duration')
    op.drop_column('learning_materials', 'word_count')
    op.alter_column('learning_predictions', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='预测更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_predicted_date'), table_name='learning_predictions')
    op.drop_index(op.f('uk_user'), table_name='learning_predictions')
    op.drop_table_comment(
        'learning_predictions',
        existing_comment='学习预测表',
        schema=None
    )
    op.add_column('material_records', sa.Column('duration_seconds', sa.Integer(), nullable=True, comment='实际学习时长'))
    op.alter_column('material_records', 'action',
               existing_type=mysql.ENUM('view', 'complete', 'dislike', collation='utf8mb4_unicode_ci'),
               type_=sa.Enum('viewed', 'completed', 'disliked', name='material_action_enum'),
               existing_nullable=False)
    op.alter_column('material_records', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_user_action'), table_name='material_records')
    op.drop_index(op.f('idx_user_created'), table_name='material_records')
    op.drop_table_comment(
        'material_records',
        existing_comment='学习资料记录表',
        schema=None
    )
    op.drop_column('material_records', 'duration')
    op.alter_column('notices', 'is_read',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               comment=None,
               existing_comment='0-未读 1-已读',
               existing_server_default=sa.text("'0'"))
    op.drop_index(op.f('idx_user_created'), table_name='notices')
    op.drop_index(op.f('idx_user_read'), table_name='notices')
    op.drop_table_comment(
        'notices',
        existing_comment='通知表',
        schema=None
    )
    op.add_column('pronunciation_content', sa.Column('title', sa.String(length=200), nullable=False, comment='内容标题'))
    op.add_column('pronunciation_content', sa.Column('content_text', sa.Text(), nullable=False, comment='跟读文本'))
    op.add_column('pronunciation_content', sa.Column('content_type', sa.Enum('word', 'sentence', name='pronunciation_content_type_enum'), nullable=False, comment='内容类型：单词/句子'))
    op.add_column('pronunciation_content', sa.Column('cefr_level', sa.String(length=5), nullable=False, comment='CEFR 难度：A1/A2/B1/B2/C1/C2'))
    op.add_column('pronunciation_content', sa.Column('category', sa.String(length=64), nullable=True, comment='分类：日常/商务/旅行/学术等'))
    op.add_column('pronunciation_content', sa.Column('phonetic_ipa', sa.String(length=500), nullable=True, comment='IPA 音标'))
    op.add_column('pronunciation_content', sa.Column('tags', sa.JSON(), nullable=True, comment='标签数组'))
    op.alter_column('pronunciation_content', 'audio_url',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               nullable=True,
               comment='标准发音音频 URL',
               existing_comment='标准音音频文件路径')
    op.alter_column('pronunciation_content', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('pronunciation_content', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('pronunciation_content', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_difficulty_mode'), table_name='pronunciation_content')
    op.drop_index(op.f('idx_is_active'), table_name='pronunciation_content')
    op.drop_table_comment(
        'pronunciation_content',
        existing_comment='发音跟读内容表',
        schema=None
    )
    op.drop_column('pronunciation_content', 'difficulty')
    op.drop_column('pronunciation_content', 'mode')
    op.drop_column('pronunciation_content', 'ipa_transcription')
    op.drop_column('pronunciation_content', 'text')
    op.drop_column('pronunciation_content', 'phoneme_annotation')
    op.add_column('pronunciation_records', sa.Column('overall_score', sa.DECIMAL(precision=5, scale=2), nullable=False, comment='综合分 0-100'))
    op.add_column('pronunciation_records', sa.Column('phoneme_score', sa.DECIMAL(precision=5, scale=2), nullable=True, comment='音素准确度分数'))
    op.add_column('pronunciation_records', sa.Column('linking_score', sa.DECIMAL(precision=5, scale=2), nullable=True, comment='连读表现分数（仅句子）'))
    op.add_column('pronunciation_records', sa.Column('correction_advice', sa.Text(), nullable=True, comment='纠音建议文本'))
    op.add_column('pronunciation_records', sa.Column('teacher_review', sa.Text(), nullable=True, comment='教师点评'))
    op.add_column('pronunciation_records', sa.Column('teacher_score', sa.DECIMAL(precision=5, scale=2), nullable=True, comment='教师评分'))
    op.alter_column('pronunciation_records', 'mode',
               existing_type=mysql.ENUM('word', 'sentence', collation='utf8mb4_unicode_ci'),
               comment='评测模式',
               existing_nullable=False)
    op.alter_column('pronunciation_records', 'audio_url',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               nullable=True,
               existing_comment='用户录音文件路径')
    op.alter_column('pronunciation_records', 'transcript',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='ASR 转写文本',
               existing_comment='Whisper转写文本',
               existing_nullable=True)
    op.alter_column('pronunciation_records', 'stress_score',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               comment='重音位置分数',
               existing_comment='重音位置分 0-100',
               existing_nullable=True)
    op.alter_column('pronunciation_records', 'intonation_score',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               comment='语调曲线分数',
               existing_comment='语调曲线分 0-100',
               existing_nullable=True)
    op.alter_column('pronunciation_records', 'rhythm_score',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               comment='节奏感分数',
               existing_comment='节奏感分 0-100',
               existing_nullable=True)
    op.alter_column('pronunciation_records', 'error_phonemes',
               existing_type=mysql.JSON(),
               comment='错误音素列表 JSON',
               existing_comment='错误音素列表JSON',
               existing_nullable=True)
    op.alter_column('pronunciation_records', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               comment=None,
               existing_comment='评测时间',
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_content'), table_name='pronunciation_records')
    op.drop_index(op.f('idx_user_created'), table_name='pronunciation_records')
    op.drop_table_comment(
        'pronunciation_records',
        existing_comment='发音评测记录表',
        schema=None
    )
    op.drop_column('pronunciation_records', 'total_score')
    op.drop_column('pronunciation_records', 'accuracy_score')
    op.drop_column('pronunciation_records', 'liaison_score')
    op.drop_column('pronunciation_records', 'feedback')
    op.alter_column('security_logs', 'user_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='关联用户（可为空，匿名违规记录）',
               existing_nullable=True)
    op.alter_column('security_logs', 'event_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               type_=sa.Enum('sensitive_content', 'rate_limit', 'auth_failure', 'suspicious_input', name='security_event_enum'),
               comment='事件类型',
               existing_comment='事件类型：sensitive_word/abnormal_request/violation',
               existing_nullable=False)
    op.alter_column('security_logs', 'detail',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               nullable=True,
               comment='事件详情',
               existing_comment='事件详情（问题文本/行为描述）')
    op.alter_column('security_logs', 'ip_address',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=45),
               comment='IP 地址',
               existing_nullable=True)
    op.alter_column('security_logs', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_created'), table_name='security_logs')
    op.drop_index(op.f('idx_event_type'), table_name='security_logs')
    op.drop_index(op.f('idx_user'), table_name='security_logs')
    op.create_foreign_key(None, 'security_logs', 'user_profiles', ['user_id'], ['id'])
    op.drop_table_comment(
        'security_logs',
        existing_comment='安全日志表',
        schema=None
    )
    op.alter_column('user_badges', 'badge_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='徽章名称',
               existing_comment='徽章名称：新手上路/坚持之星/发音突破/进步达人/配音达人/满分挑战/学霸成就',
               existing_nullable=False)
    op.drop_index(op.f('idx_badge_type'), table_name='user_badges')
    op.drop_index(op.f('uk_user_badge'), table_name='user_badges')
    op.drop_table_comment(
        'user_badges',
        existing_comment='用户徽章表',
        schema=None
    )
    op.alter_column('user_profiles', 'interests',
               existing_type=mysql.JSON(),
               comment=None,
               existing_comment='兴趣标签数组，如["音乐","旅行"]',
               existing_nullable=True)
    op.alter_column('user_profiles', 'level_self',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               comment=None,
               existing_comment='用户自评等级：初级/中级/高级',
               existing_nullable=True)
    op.alter_column('user_profiles', 'level_test',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=5),
               comment=None,
               existing_comment='测评CEFR等级：A1/A2/B1/B2/C1/C2',
               existing_nullable=True)
    op.alter_column('user_profiles', 'level_final',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=5),
               comment=None,
               existing_comment='综合等级，以level_test为准',
               existing_nullable=True)
    op.alter_column('user_profiles', 'assessment_completed',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Integer(),
               comment=None,
               existing_comment='0-未完成 1-已完成',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('user_profiles', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Integer(),
               comment=None,
               existing_comment='0-禁用 1-正常',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('user_profiles', 'version',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='乐观锁版本号',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('user_profiles', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('user_profiles', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_is_active'), table_name='user_profiles')
    op.drop_index(op.f('idx_level_final'), table_name='user_profiles')
    op.drop_index(op.f('idx_role'), table_name='user_profiles')
    op.drop_table_comment(
        'user_profiles',
        existing_comment='用户表',
        schema=None
    )
    op.alter_column('user_scores', 'description',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment=None,
               existing_comment='积分说明文字',
               existing_nullable=True,
               existing_server_default=sa.text("''"))
    op.drop_index(op.f('idx_action_type'), table_name='user_scores')
    op.drop_index(op.f('idx_user_created'), table_name='user_scores')
    op.drop_table_comment(
        'user_scores',
        existing_comment='积分记录表',
        schema=None
    )
    op.alter_column('user_skill_scores', 'user_id',
               existing_type=mysql.INTEGER(),
               comment='用户 ID',
               existing_nullable=False)
    op.alter_column('user_skill_scores', 'dimension',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               comment='技能维度：listening / speaking / reading / grammar',
               existing_comment='listening/speaking/reading/grammar',
               existing_nullable=False)
    op.alter_column('user_skill_scores', 'skill_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               comment='具体技能名，如 pronunciation:phoneme_accuracy',
               existing_comment='pronunciation:phoneme_accuracy',
               existing_nullable=False)
    op.alter_column('user_skill_scores', 'score',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               comment='分数 0-100',
               existing_comment='0-100',
               existing_nullable=False)
    op.alter_column('user_skill_scores', 'source',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               comment='来源：pronunciation / conversation / daily_task / assessment',
               existing_comment='pronunciation/conversation/daily_task/assessment',
               existing_nullable=False)
    op.alter_column('user_skill_scores', 'source_id',
               existing_type=mysql.INTEGER(),
               comment='来源记录 ID',
               existing_nullable=True)
    op.alter_column('user_skill_scores', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_user_created'), table_name='user_skill_scores')
    op.drop_index(op.f('idx_user_dimension'), table_name='user_skill_scores')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_user_dimension'), 'user_skill_scores', ['user_id', 'dimension'], unique=False)
    op.create_index(op.f('idx_user_created'), 'user_skill_scores', ['user_id', 'created_at'], unique=False)
    op.alter_column('user_skill_scores', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('user_skill_scores', 'source_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='来源记录 ID',
               existing_nullable=True)
    op.alter_column('user_skill_scores', 'source',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               comment='pronunciation/conversation/daily_task/assessment',
               existing_comment='来源：pronunciation / conversation / daily_task / assessment',
               existing_nullable=False)
    op.alter_column('user_skill_scores', 'score',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               comment='0-100',
               existing_comment='分数 0-100',
               existing_nullable=False)
    op.alter_column('user_skill_scores', 'skill_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               comment='pronunciation:phoneme_accuracy',
               existing_comment='具体技能名，如 pronunciation:phoneme_accuracy',
               existing_nullable=False)
    op.alter_column('user_skill_scores', 'dimension',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               comment='listening/speaking/reading/grammar',
               existing_comment='技能维度：listening / speaking / reading / grammar',
               existing_nullable=False)
    op.alter_column('user_skill_scores', 'user_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='用户 ID',
               existing_nullable=False)
    op.create_table_comment(
        'user_scores',
        '积分记录表',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_user_created'), 'user_scores', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('idx_action_type'), 'user_scores', ['action_type'], unique=False)
    op.alter_column('user_scores', 'description',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment='积分说明文字',
               existing_nullable=True,
               existing_server_default=sa.text("''"))
    op.create_table_comment(
        'user_profiles',
        '用户表',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_role'), 'user_profiles', ['role'], unique=False)
    op.create_index(op.f('idx_level_final'), 'user_profiles', ['level_final'], unique=False)
    op.create_index(op.f('idx_is_active'), 'user_profiles', ['is_active'], unique=False)
    op.alter_column('user_profiles', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('user_profiles', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('user_profiles', 'version',
               existing_type=mysql.INTEGER(),
               comment='乐观锁版本号',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('user_profiles', 'is_active',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=1),
               comment='0-禁用 1-正常',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('user_profiles', 'assessment_completed',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=1),
               comment='0-未完成 1-已完成',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('user_profiles', 'level_final',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=5),
               comment='综合等级，以level_test为准',
               existing_nullable=True)
    op.alter_column('user_profiles', 'level_test',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=5),
               comment='测评CEFR等级：A1/A2/B1/B2/C1/C2',
               existing_nullable=True)
    op.alter_column('user_profiles', 'level_self',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               comment='用户自评等级：初级/中级/高级',
               existing_nullable=True)
    op.alter_column('user_profiles', 'interests',
               existing_type=mysql.JSON(),
               comment='兴趣标签数组，如["音乐","旅行"]',
               existing_nullable=True)
    op.create_table_comment(
        'user_badges',
        '用户徽章表',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('uk_user_badge'), 'user_badges', ['user_id', 'badge_type'], unique=True)
    op.create_index(op.f('idx_badge_type'), 'user_badges', ['badge_type'], unique=False)
    op.alter_column('user_badges', 'badge_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='徽章名称：新手上路/坚持之星/发音突破/进步达人/配音达人/满分挑战/学霸成就',
               existing_comment='徽章名称',
               existing_nullable=False)
    op.create_table_comment(
        'security_logs',
        '安全日志表',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'security_logs', type_='foreignkey')
    op.create_index(op.f('idx_user'), 'security_logs', ['user_id'], unique=False)
    op.create_index(op.f('idx_event_type'), 'security_logs', ['event_type'], unique=False)
    op.create_index(op.f('idx_created'), 'security_logs', ['created_at'], unique=False)
    op.alter_column('security_logs', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('security_logs', 'ip_address',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=45),
               comment=None,
               existing_comment='IP 地址',
               existing_nullable=True)
    op.alter_column('security_logs', 'detail',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               nullable=False,
               comment='事件详情（问题文本/行为描述）',
               existing_comment='事件详情')
    op.alter_column('security_logs', 'event_type',
               existing_type=sa.Enum('sensitive_content', 'rate_limit', 'auth_failure', 'suspicious_input', name='security_event_enum'),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='事件类型：sensitive_word/abnormal_request/violation',
               existing_comment='事件类型',
               existing_nullable=False)
    op.alter_column('security_logs', 'user_id',
               existing_type=mysql.INTEGER(),
               comment='关联用户（可为空，匿名违规记录）',
               existing_nullable=True)
    op.add_column('pronunciation_records', sa.Column('feedback', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True, comment='中文纠音建议文本'))
    op.add_column('pronunciation_records', sa.Column('liaison_score', mysql.DECIMAL(precision=5, scale=2), nullable=True, comment='连读表现分 0-100（仅句子）'))
    op.add_column('pronunciation_records', sa.Column('accuracy_score', mysql.DECIMAL(precision=5, scale=2), nullable=True, comment='音素准确度 0-100'))
    op.add_column('pronunciation_records', sa.Column('total_score', mysql.DECIMAL(precision=5, scale=2), nullable=True, comment='加权综合分 0-100'))
    op.create_table_comment(
        'pronunciation_records',
        '发音评测记录表',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_user_created'), 'pronunciation_records', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('idx_content'), 'pronunciation_records', ['content_id'], unique=False)
    op.alter_column('pronunciation_records', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               comment='评测时间',
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('pronunciation_records', 'error_phonemes',
               existing_type=mysql.JSON(),
               comment='错误音素列表JSON',
               existing_comment='错误音素列表 JSON',
               existing_nullable=True)
    op.alter_column('pronunciation_records', 'rhythm_score',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               comment='节奏感分 0-100',
               existing_comment='节奏感分数',
               existing_nullable=True)
    op.alter_column('pronunciation_records', 'intonation_score',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               comment='语调曲线分 0-100',
               existing_comment='语调曲线分数',
               existing_nullable=True)
    op.alter_column('pronunciation_records', 'stress_score',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               comment='重音位置分 0-100',
               existing_comment='重音位置分数',
               existing_nullable=True)
    op.alter_column('pronunciation_records', 'transcript',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Whisper转写文本',
               existing_comment='ASR 转写文本',
               existing_nullable=True)
    op.alter_column('pronunciation_records', 'audio_url',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               nullable=False,
               existing_comment='用户录音文件路径')
    op.alter_column('pronunciation_records', 'mode',
               existing_type=mysql.ENUM('word', 'sentence', collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='评测模式',
               existing_nullable=False)
    op.drop_column('pronunciation_records', 'teacher_score')
    op.drop_column('pronunciation_records', 'teacher_review')
    op.drop_column('pronunciation_records', 'correction_advice')
    op.drop_column('pronunciation_records', 'linking_score')
    op.drop_column('pronunciation_records', 'phoneme_score')
    op.drop_column('pronunciation_records', 'overall_score')
    op.add_column('pronunciation_content', sa.Column('phoneme_annotation', mysql.JSON(), nullable=True, comment='音素级标注JSON'))
    op.add_column('pronunciation_content', sa.Column('text', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=False, comment='跟读文本（单词或句子）'))
    op.add_column('pronunciation_content', sa.Column('ipa_transcription', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True, comment='国际音标注音'))
    op.add_column('pronunciation_content', sa.Column('mode', mysql.ENUM('word', 'sentence', collation='utf8mb4_unicode_ci'), nullable=False))
    op.add_column('pronunciation_content', sa.Column('difficulty', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=5), nullable=False, comment='难度等级：A1/A2/B1/B2'))
    op.create_table_comment(
        'pronunciation_content',
        '发音跟读内容表',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_is_active'), 'pronunciation_content', ['is_active'], unique=False)
    op.create_index(op.f('idx_difficulty_mode'), 'pronunciation_content', ['difficulty', 'mode'], unique=False)
    op.alter_column('pronunciation_content', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('pronunciation_content', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('pronunciation_content', 'is_active',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('pronunciation_content', 'audio_url',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               nullable=False,
               comment='标准音音频文件路径',
               existing_comment='标准发音音频 URL')
    op.drop_column('pronunciation_content', 'tags')
    op.drop_column('pronunciation_content', 'phonetic_ipa')
    op.drop_column('pronunciation_content', 'category')
    op.drop_column('pronunciation_content', 'cefr_level')
    op.drop_column('pronunciation_content', 'content_type')
    op.drop_column('pronunciation_content', 'content_text')
    op.drop_column('pronunciation_content', 'title')
    op.create_table_comment(
        'notices',
        '通知表',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_user_read'), 'notices', ['user_id', 'is_read'], unique=False)
    op.create_index(op.f('idx_user_created'), 'notices', ['user_id', 'created_at'], unique=False)
    op.alter_column('notices', 'is_read',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               comment='0-未读 1-已读',
               existing_server_default=sa.text("'0'"))
    op.add_column('material_records', sa.Column('duration', mysql.SMALLINT(), autoincrement=False, nullable=True, comment='实际学习时长（秒）'))
    op.create_table_comment(
        'material_records',
        '学习资料记录表',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_user_created'), 'material_records', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('idx_user_action'), 'material_records', ['user_id', 'action'], unique=False)
    op.alter_column('material_records', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('material_records', 'action',
               existing_type=sa.Enum('viewed', 'completed', 'disliked', name='material_action_enum'),
               type_=mysql.ENUM('view', 'complete', 'dislike', collation='utf8mb4_unicode_ci'),
               existing_nullable=False)
    op.drop_column('material_records', 'duration_seconds')
    op.create_table_comment(
        'learning_predictions',
        '学习预测表',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('uk_user'), 'learning_predictions', ['user_id'], unique=True)
    op.create_index(op.f('idx_predicted_date'), 'learning_predictions', ['predicted_date'], unique=False)
    op.alter_column('learning_predictions', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment='预测更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.add_column('learning_materials', sa.Column('word_count', mysql.SMALLINT(), autoincrement=False, nullable=True, comment='词数，文章适用'))
    op.add_column('learning_materials', sa.Column('duration', mysql.SMALLINT(), autoincrement=False, nullable=True, comment='时长（分钟），视频/音频适用'))
    op.add_column('learning_materials', sa.Column('type', mysql.ENUM('video', 'article', 'audio', collation='utf8mb4_unicode_ci'), nullable=False))
    op.add_column('learning_materials', sa.Column('related_dimension', mysql.ENUM('pronunciation', 'listening', 'grammar', 'fluency', collation='utf8mb4_unicode_ci'), nullable=False))
    op.add_column('learning_materials', sa.Column('difficulty', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=5), nullable=False, comment='CEFR难度：A1/A2/B1/B2'))
    op.create_table_comment(
        'learning_materials',
        '学习资料表',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_type_difficulty'), 'learning_materials', ['type', 'difficulty'], unique=False)
    op.create_index(op.f('idx_is_active'), 'learning_materials', ['is_active'], unique=False)
    op.create_index(op.f('idx_dimension'), 'learning_materials', ['related_dimension'], unique=False)
    op.alter_column('learning_materials', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('learning_materials', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('learning_materials', 'is_active',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('learning_materials', 'tags',
               existing_type=mysql.JSON(),
               comment='内容标签数组JSON',
               existing_comment='标签数组',
               existing_nullable=True)
    op.alter_column('learning_materials', 'url',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               comment=None,
               existing_comment='资料链接',
               existing_nullable=False)
    op.alter_column('learning_materials', 'title',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment=None,
               existing_comment='资料标题',
               existing_nullable=False)
    op.drop_column('learning_materials', 'focus_dimensions')
    op.drop_column('learning_materials', 'duration_seconds')
    op.drop_column('learning_materials', 'category')
    op.drop_column('learning_materials', 'cefr_level')
    op.drop_column('learning_materials', 'material_type')
    op.drop_column('learning_materials', 'description')
    op.create_table_comment(
        'groups',
        '学习小组表',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_level_range'), 'groups', ['level_range'], unique=False)
    op.create_index(op.f('idx_is_archived'), 'groups', ['is_archived'], unique=False)
    op.alter_column('groups', 'is_archived',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               comment='0-正常 1-已归档',
               existing_comment='是否归档',
               existing_server_default=sa.text("'0'"))
    op.alter_column('groups', 'member_count',
               existing_type=mysql.SMALLINT(),
               nullable=False,
               comment=None,
               existing_comment='成员数',
               existing_server_default=sa.text("'0'"))
    op.alter_column('groups', 'max_members',
               existing_type=mysql.SMALLINT(),
               nullable=False,
               comment=None,
               existing_comment='最大人数',
               existing_server_default=sa.text("'20'"))
    op.alter_column('groups', 'tags',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment=None,
               existing_comment='标签，逗号分隔',
               existing_nullable=True,
               existing_server_default=sa.text("''"))
    op.alter_column('groups', 'schedule',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment=None,
               existing_comment='活动时间',
               existing_nullable=True,
               existing_server_default=sa.text("''"))
    op.alter_column('groups', 'level_range',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment='等级范围如 A1-B1',
               existing_comment='等级范围如 A1-C1',
               existing_nullable=True,
               existing_server_default=sa.text("''"))
    op.alter_column('groups', 'description',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               comment=None,
               existing_comment='小组简介',
               existing_nullable=True,
               existing_server_default=sa.text("''"))
    op.alter_column('groups', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment=None,
               existing_comment='小组名称',
               existing_nullable=False)
    op.create_table_comment(
        'group_members',
        '小组成员表',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('uk_group_user'), 'group_members', ['group_id', 'user_id'], unique=True)
    op.create_index(op.f('idx_user'), 'group_members', ['user_id'], unique=False)
    op.alter_column('group_members', 'role',
               existing_type=sa.String(length=10),
               type_=mysql.ENUM('owner', 'member', collation='utf8mb4_unicode_ci'),
               nullable=False,
               comment=None,
               existing_comment='owner/member',
               existing_server_default=sa.text("'member'"))
    op.add_column('faq_entries', sa.Column('priority', mysql.TINYINT(), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='展示优先级，越大越靠前'))
    op.create_table_comment(
        'faq_entries',
        'FAQ条目表',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_is_active'), 'faq_entries', ['is_active'], unique=False)
    op.create_index(op.f('idx_category_priority'), 'faq_entries', ['category', 'priority'], unique=False)
    op.alter_column('faq_entries', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('faq_entries', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('faq_entries', 'is_active',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('faq_entries', 'category',
               existing_type=sa.Enum('product_use', 'study_advice', 'tech_issue', 'refund', 'general', name='faq_category_enum'),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='分类：product_use/study_advice/tech_issue/account',
               existing_comment='问题分类',
               existing_nullable=False)
    op.alter_column('faq_entries', 'answer',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='回答文本',
               existing_nullable=False)
    op.alter_column('faq_entries', 'question',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               comment=None,
               existing_comment='问题文本',
               existing_nullable=False)
    op.drop_column('faq_entries', 'sort_order')
    op.create_table_comment(
        'dubbing_records',
        '配音记录表',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_user_created'), 'dubbing_records', ['user_id', 'created_at'], unique=False)
    op.alter_column('dubbing_records', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='配音时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('dubbing_records', 'total_score',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               comment='综合评分 0-100',
               existing_nullable=True)
    op.alter_column('dubbing_records', 'emotion_score',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               comment='情感匹配度 0-100',
               existing_nullable=True)
    op.alter_column('dubbing_records', 'intonation_score',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               comment='语调相似度 0-100',
               existing_nullable=True)
    op.alter_column('dubbing_records', 'pronunciation_score',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               comment='发音相似度 0-100',
               existing_nullable=True)
    op.create_table_comment(
        'dubbing_content',
        '配音内容表',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_is_active'), 'dubbing_content', ['is_active'], unique=False)
    op.create_index(op.f('idx_difficulty'), 'dubbing_content', ['difficulty'], unique=False)
    op.alter_column('dubbing_content', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('dubbing_content', 'duration',
               existing_type=sa.SmallInteger(),
               type_=mysql.TINYINT(),
               existing_comment='片段时长（秒）5-20',
               existing_nullable=False)
    op.alter_column('dubbing_content', 'source',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment='来源：电影/动画/演讲名称',
               existing_nullable=True,
               existing_server_default=sa.text("''"))
    op.add_column('conversation_sessions', sa.Column('score_breakdown', mysql.JSON(), nullable=True, comment='评分维度明细JSON'))
    op.add_column('conversation_sessions', sa.Column('total_score', mysql.DECIMAL(precision=5, scale=2), nullable=True, comment='对话结束综合评分'))
    op.add_column('conversation_sessions', sa.Column('scene_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='场景ID：1-自我介绍/2-问路/3-购物/4-餐厅'))
    op.create_table_comment(
        'conversation_sessions',
        '对话会话表',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'conversation_sessions', type_='unique')
    op.create_index(op.f('idx_user_status'), 'conversation_sessions', ['user_id', 'status'], unique=False)
    op.create_index(op.f('idx_scene'), 'conversation_sessions', ['scene_id'], unique=False)
    op.alter_column('conversation_sessions', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('conversation_sessions', 'ended_at',
               existing_type=mysql.DATETIME(),
               comment='对话结束时间',
               existing_nullable=True)
    op.alter_column('conversation_sessions', 'started_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               comment='对话开始时间',
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('conversation_sessions', 'role_id',
               existing_type=mysql.INTEGER(),
               comment='角色ID（角色扮演会话用），NULL为普通对话',
               existing_comment='角色扮演角色 ID（仅角色扮演场景）',
               existing_nullable=True)
    op.drop_column('conversation_sessions', 'updated_at')
    op.drop_column('conversation_sessions', 'improvement_suggestions')
    op.drop_column('conversation_sessions', 'score_overall')
    op.drop_column('conversation_sessions', 'score_engagement')
    op.drop_column('conversation_sessions', 'score_vocabulary')
    op.drop_column('conversation_sessions', 'score_grammar')
    op.drop_column('conversation_sessions', 'score_pronunciation')
    op.drop_column('conversation_sessions', 'round_count')
    op.drop_column('conversation_sessions', 'cefr_level')
    op.drop_column('conversation_sessions', 'scene')
    op.drop_column('conversation_sessions', 'session_uuid')
    op.add_column('conversation_messages', sa.Column('text', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=False))
    op.add_column('conversation_messages', sa.Column('message_order', mysql.SMALLINT(), autoincrement=False, nullable=False, comment='消息序号 1-10'))
    op.add_column('conversation_messages', sa.Column('confidence', mysql.DECIMAL(precision=3, scale=2), nullable=True, comment='Whisper转写置信度 0-1'))
    op.create_table_comment(
        'conversation_messages',
        '对话消息表',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_session_order'), 'conversation_messages', ['session_id', 'message_order'], unique=False)
    op.alter_column('conversation_messages', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               comment='消息时间',
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('conversation_messages', 'fluency_scores',
               existing_type=mysql.JSON(),
               comment='流利度五维评分JSON',
               existing_comment='流利度五维评分 JSON',
               existing_nullable=True)
    op.alter_column('conversation_messages', 'grammar_check',
               existing_type=mysql.JSON(),
               comment='语法检查结果JSON（含纠错+润色）',
               existing_comment='语法纠错结果 JSON',
               existing_nullable=True)
    op.alter_column('conversation_messages', 'audio_url',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               comment='语音消息文件路径',
               existing_comment='音频 URL（用户录音或 TTS）',
               existing_nullable=True)
    op.alter_column('conversation_messages', 'role',
               existing_type=sa.Enum('user', 'assistant', name='message_role_enum'),
               type_=mysql.ENUM('user', 'ai', collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='消息角色',
               existing_nullable=False)
    op.drop_column('conversation_messages', 'score')
    op.drop_column('conversation_messages', 'content_text')
    op.drop_column('conversation_messages', 'round_number')
    op.create_table_comment(
        'classes',
        '班级表',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_teacher'), 'classes', ['teacher_id'], unique=False)
    op.create_index(op.f('idx_is_active'), 'classes', ['is_active'], unique=False)
    op.alter_column('classes', 'is_active',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=1),
               nullable=False,
               comment=None,
               existing_comment='0-停用 1-启用',
               existing_server_default=sa.text("'1'"))
    op.alter_column('classes', 'student_count',
               existing_type=mysql.SMALLINT(),
               nullable=False,
               comment=None,
               existing_comment='学生数',
               existing_server_default=sa.text("'0'"))
    op.alter_column('classes', 'invite_code',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment='邀请码（唯一）',
               existing_comment='邀请码',
               existing_nullable=False)
    op.alter_column('classes', 'description',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               comment=None,
               existing_comment='班级描述',
               existing_nullable=True,
               existing_server_default=sa.text("''"))
    op.alter_column('classes', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment=None,
               existing_comment='班级名称',
               existing_nullable=False)
    op.create_table_comment(
        'class_students',
        '班级学生表',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('uk_class_user'), 'class_students', ['class_id', 'user_id'], unique=True)
    op.create_index(op.f('idx_user'), 'class_students', ['user_id'], unique=False)
    op.create_table_comment(
        'assignments',
        '作业表',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_due_date'), 'assignments', ['due_date'], unique=False)
    op.create_index(op.f('idx_class_due'), 'assignments', ['class_id', 'due_date'], unique=False)
    op.alter_column('assignments', 'completion_rate',
               existing_type=mysql.DECIMAL(precision=4, scale=1),
               nullable=False,
               existing_comment='完成率百分比',
               existing_server_default=sa.text("'0.0'"))
    op.alter_column('assignments', 'description',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='作业描述',
               existing_nullable=True)
    op.alter_column('assignments', 'title',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment=None,
               existing_comment='作业标题',
               existing_nullable=False)
    op.create_table_comment(
        'assignment_submissions',
        '作业提交表',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('uk_assignment_user'), 'assignment_submissions', ['assignment_id', 'user_id'], unique=True)
    op.create_index(op.f('idx_status'), 'assignment_submissions', ['status'], unique=False)
    op.alter_column('assignment_submissions', 'status',
               existing_type=mysql.ENUM('submitted', 'reviewed', collation='utf8mb4_unicode_ci'),
               nullable=False,
               existing_server_default=sa.text("'submitted'"))
    op.alter_column('assignment_submissions', 'teacher_score',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               comment='教师评分 0-100',
               existing_comment='教师评分',
               existing_nullable=True)
    op.alter_column('assignment_submissions', 'teacher_feedback',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='教师点评文字',
               existing_comment='教师点评',
               existing_nullable=True)
    op.alter_column('assignment_submissions', 'score',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               comment='AI评分 0-100',
               existing_comment='AI评分',
               existing_nullable=True)
    op.create_table_comment(
        'assessment_records',
        '测评记录表',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_user_session'), 'assessment_records', ['user_id', 'session_id'], unique=False)
    op.create_index(op.f('idx_session'), 'assessment_records', ['session_id'], unique=False)
    op.alter_column('assessment_records', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               comment='作答时间',
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('assessment_records', 'question_order',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(),
               existing_comment='题号 1-10',
               existing_nullable=False)
    op.alter_column('assessment_records', 'transcript',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='口语题Whisper转写文本',
               existing_comment='口语题转写文本',
               existing_nullable=True)
    op.alter_column('assessment_records', 'is_correct',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=1),
               existing_comment='客观题是否正确，口语题为NULL',
               existing_nullable=True)
    op.alter_column('assessment_records', 'user_answer',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='用户答案（选项ID 或 录音URL）',
               existing_comment='选项ID 或 录音URL',
               existing_nullable=True)
    op.alter_column('assessment_records', 'session_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               comment='测评会话UUID，一次测评对应一个',
               existing_comment='测评会话UUID',
               existing_nullable=False)
    op.create_table_comment(
        'assessment_questions',
        '测评题库表',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_is_active'), 'assessment_questions', ['is_active'], unique=False)
    op.create_index(op.f('idx_dimension_difficulty'), 'assessment_questions', ['dimension', 'difficulty'], unique=False)
    op.alter_column('assessment_questions', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('assessment_questions', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('assessment_questions', 'is_active',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('assessment_questions', 'correct_option',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(),
               existing_comment='正确选项序号 1-4',
               existing_nullable=False)
    op.alter_column('assessment_questions', 'options',
               existing_type=mysql.JSON(),
               comment='客观题选项数组，每题4个选项',
               existing_nullable=False)
    op.add_column('admin_logs', sa.Column('ip_address', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=45), nullable=True))
    op.create_table_comment(
        'admin_logs',
        '管理员操作日志表',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_target'), 'admin_logs', ['target_type', 'target_id'], unique=False)
    op.create_index(op.f('idx_admin_created'), 'admin_logs', ['admin_id', 'created_at'], unique=False)
    op.create_index(op.f('idx_action'), 'admin_logs', ['action'], unique=False)
    op.alter_column('admin_logs', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='操作时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('admin_logs', 'target_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='操作对象类型：user/content/class等',
               existing_comment='操作对象类型',
               existing_nullable=False)
    op.alter_column('admin_logs', 'action',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment='操作类型：user_disable/content_edit/class_create等',
               existing_comment='操作类型',
               existing_nullable=False)
    op.create_table('challenge_topics',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='发起人用户ID'),
    sa.Column('content_text', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=False, comment='挑战跟读文本'),
    sa.Column('audio_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=False, comment='发起人示范录音'),
    sa.Column('status', mysql.ENUM('active', 'ended'), server_default=sa.text("'active'"), nullable=False),
    sa.Column('participant_count', mysql.SMALLINT(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('expires_at', mysql.DATETIME(), nullable=False, comment='过期时间（创建后7天）'),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], name=op.f('fk_challenge_user')),
    sa.PrimaryKeyConstraint('id'),
    comment='语音挑战表',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='语音挑战表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('idx_status_expires'), 'challenge_topics', ['status', 'expires_at'], unique=False)
    op.create_table('system_config',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('config_key', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False, comment='配置键名'),
    sa.Column('config_value', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=False, comment='配置值'),
    sa.Column('config_type', mysql.ENUM('string', 'integer', 'boolean', 'json'), server_default=sa.text("'string'"), nullable=False),
    sa.Column('description', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), server_default=sa.text("''"), nullable=True, comment='配置说明'),
    sa.Column('is_public', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='是否可公开（0-仅管理员 1-前端可读）'),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='系统配置表',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='系统配置表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('uk_config_key'), 'system_config', ['config_key'], unique=True)
    op.create_table('discussion_topics',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=False),
    sa.Column('content', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('category', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False, comment='分类：learning/experience/question/sharing'),
    sa.Column('view_count', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('comment_count', mysql.SMALLINT(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('is_pinned', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], name=op.f('fk_topic_user')),
    sa.PrimaryKeyConstraint('id'),
    comment='讨论主题表',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='讨论主题表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('idx_is_pinned_created'), 'discussion_topics', ['is_pinned', 'created_at'], unique=False)
    op.create_index(op.f('idx_category'), 'discussion_topics', ['category'], unique=False)
    op.create_table('challenge_participations',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('challenge_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('audio_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=False, comment='参与录音文件'),
    sa.Column('pronunciation_score', mysql.DECIMAL(precision=5, scale=2), nullable=True, comment='发音评分 0-100'),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenge_topics.id'], name=op.f('fk_chal_part_challenge')),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], name=op.f('fk_chal_part_user')),
    sa.PrimaryKeyConstraint('id'),
    comment='挑战参与表',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='挑战参与表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('uk_challenge_user'), 'challenge_participations', ['challenge_id', 'user_id'], unique=True)
    op.create_index(op.f('idx_challenge_score'), 'challenge_participations', ['challenge_id', 'pronunciation_score'], unique=False)
    op.create_table('discussion_comments',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('topic_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('parent_id', mysql.INTEGER(), autoincrement=False, nullable=True, comment='父评论ID（回复嵌套），NULL为顶级'),
    sa.Column('is_reported', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['discussion_comments.id'], name=op.f('fk_comment_parent')),
    sa.ForeignKeyConstraint(['topic_id'], ['discussion_topics.id'], name=op.f('fk_comment_topic')),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], name=op.f('fk_comment_user')),
    sa.PrimaryKeyConstraint('id'),
    comment='讨论评论表',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='讨论评论表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('idx_topic_created'), 'discussion_comments', ['topic_id', 'created_at'], unique=False)
    op.create_index(op.f('idx_parent'), 'discussion_comments', ['parent_id'], unique=False)
    op.create_table('customer_service_sessions',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('answer', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('category', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True, comment='问题分类：product_use/study_advice/tech_issue/refund/off_topic'),
    sa.Column('need_manual', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='是否需要转人工'),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], name=op.f('fk_cs_session_user')),
    sa.PrimaryKeyConstraint('id'),
    comment='客服会话表',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='客服会话表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('idx_user_created'), 'customer_service_sessions', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('idx_need_manual'), 'customer_service_sessions', ['need_manual'], unique=False)
    op.create_index(op.f('idx_category'), 'customer_service_sessions', ['category'], unique=False)
    op.drop_table('support_sessions')
    # ### end Alembic commands ###
